Alex and serena/s1 f1 groundwork schemas
GTBitsOfGood/hdg-chatbot pull request #1
Opened 2021-02-04 19:38 UTC by alexb8z

Groundwork schemas complete for UserState and ChatbotMessage. Selected types for fields, but these can be changed later if needed (for example, if an object would work better than an array for images or something like that).

2021-02-05 03:40 UTC, Fattimo requested changes

2021-02-05 03:40 UTC, Fattimo commented on models/ChatbotMessage.ts
> +  nextMessages: { type: Array, required: true },
https://mongoosejs.com/docs/schematypes.html#maps

Great work on the rest of this PR, everything looks really good. One small adjustment here: I talked to Alex about this issue during our 1-1, but I was thinking about we should go about actually splitting into the correct message. An array is one way to do it, but we'd somehow need to transmit and store a correct index, which is possible in some way, but seems very clunky as I think about it more.

I think the best way to do it is through a map (or object, but it's referred to as a map in Mongoose documentation oops) which I've linked above. Additionally, be sure to type the content of arrays as done on line 54 in this previous project here: https://github.com/GTBitsOfGood/gen-soln/blob/develop/server/models/nonprofit.js using `type: Schema.ObjectId, ref: 'ChatbotMessage'`.

2021-02-05 03:40 UTC, Fattimo commented on models/ChatbotMessage.ts
> +  previousMessage: { type: String, required: true },
Type this as a reference to the key of another ChatbotMessage, same as explained above

2021-02-05 03:40 UTC, Fattimo commented on models/ChatbotMessage.ts
> +  images: { type: Array, required: false },
Type this array as explained below

2021-02-05 03:40 UTC, Fattimo commented on models/UserState.ts
> +  currMessage: { type: String, required: true },
Type this as a key to a message as explained above

2021-02-05 04:17 UTC, Arthelon commented on package.json
> +    "n": "^7.0.1",
Don't think this dependency was meant to be included (probably meant to install it globally)

2021-02-05 04:17 UTC, Arthelon commented on package.json
> +    "@types/mongoose": "^5.10.3",
all `@types` packages should be installed as devDependencies

2021-02-06 18:33 UTC, Fattimo approved these changes
Great job!

2021-02-06 18:33 UTC, merged